name: reddit_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  google_sign_in: ^6.3.0
  flutter_riverpod: ^2.6.1
  fpdart: ^1.1.1
  routemaster: ^1.0.1
  dotted_border: ^3.1.0
  file_picker: ^10.2.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
