// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU1ay24Tph-hY6seCvMYVfoppAptcEExw',
    appId: '1:592572950572:web:fbcf58b01cc7b51bdcc989',
    messagingSenderId: '592572950572',
    projectId: 'reddit-flutter-a1005',
    authDomain: 'reddit-flutter-a1005.firebaseapp.com',
    storageBucket: 'reddit-flutter-a1005.firebasestorage.app',
    measurementId: 'G-983CQQZMS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNjd9uUJdtig8IVqX8toDnR6C7kupELhs',
    appId: '1:592572950572:android:ff3d94a485293091dcc989',
    messagingSenderId: '592572950572',
    projectId: 'reddit-flutter-a1005',
    storageBucket: 'reddit-flutter-a1005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0latGyGNTjbVAa4asDvCpthstE2tFM9w',
    appId: '1:592572950572:ios:1a8f145b083e466cdcc989',
    messagingSenderId: '592572950572',
    projectId: 'reddit-flutter-a1005',
    storageBucket: 'reddit-flutter-a1005.firebasestorage.app',
    iosBundleId: 'com.example.redditFlutter',
  );
}
