// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeOjfK81PQ2XuLbu_b9_mofNxnhSxGq-U',
    appId: '1:589370519862:web:a55ab8944abdff4dd98397',
    messagingSenderId: '589370519862',
    projectId: 'reddit-clone-5fa87',
    authDomain: 'reddit-clone-5fa87.firebaseapp.com',
    storageBucket: 'reddit-clone-5fa87.firebasestorage.app',
    measurementId: 'G-E5N3CYS1JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvGpV-QpGLqqbTjHJiZc9KHOTNLqd2Xcw',
    appId: '1:589370519862:android:a394ab44517ff520d98397',
    messagingSenderId: '589370519862',
    projectId: 'reddit-clone-5fa87',
    storageBucket: 'reddit-clone-5fa87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzPiR3zCgWktDYA6vZO0_75WpfiUON-Q4',
    appId: '1:589370519862:ios:40059a92e8082bdfd98397',
    messagingSenderId: '589370519862',
    projectId: 'reddit-clone-5fa87',
    storageBucket: 'reddit-clone-5fa87.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzPiR3zCgWktDYA6vZO0_75WpfiUON-Q4',
    appId: '1:589370519862:ios:40059a92e8082bdfd98397',
    messagingSenderId: '589370519862',
    projectId: 'reddit-clone-5fa87',
    storageBucket: 'reddit-clone-5fa87.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeOjfK81PQ2XuLbu_b9_mofNxnhSxGq-U',
    appId: '1:589370519862:web:445128e4f7246bf5d98397',
    messagingSenderId: '589370519862',
    projectId: 'reddit-clone-5fa87',
    authDomain: 'reddit-clone-5fa87.firebaseapp.com',
    storageBucket: 'reddit-clone-5fa87.firebasestorage.app',
    measurementId: 'G-FF8EX9X7ER',
  );
}
